### ISSUE TITLE
Some random issues stuff

### ISSUE THREAD

**Issue by thelegitdolt** [davidjjung/irregularchef#2]
1. Thrasher fin soup stacks to 64

2.  turkey pot pie, hunter's casserole, turtle gallimaufry, and thrasher soups uses cooked meats instead of raw meats, as is the case for FD cooking pot recipes using meat.

3. Dirt cups and purple cow floats do not obey the mug.json model provided in FD.

4. Kind of a nitpick, but dirt cup and purple cow float perhaps shouldn't restore hunger and saturation? Hot cocoa doesn't, the upcoming apple cider and melon juice doesn't, and all the abnormals delight mugs doesn't either.

**Comment by davidjjung** [comment]
Oh goodness, I hadn't hooked up irregularchef's git to the discord i get git notifs in lol. sorry about that!

1. fixed iirc
2. intentional, but i'll see if it
3. whoops, i'll get on that when i can
4. oh shoot, slipped my mind. i still think dirt cups will restore food values (since they're a "solid" food despite using a mug), but i'm down to remove it from purple cow floats

**Comment by thelegitdolt** [comment]
I swear it thrasher soup stacked to 64 in the latest version still?
could have just accidentally not updated but i doubt it
But yeah dirt cup restoring hunger makes sense
